import { Costume } from './types';

export const COSTUMES: Costume[] = [
  {
    id: '1',
    name: 'Seragam PDU Paskibraka Putra (Lengkap)',
    category: 'fullset',
    price: 350000,
    image: 'https://picsum.photos/id/1005/600/800',
    description: 'Pakaian Dinas Upacara (PDU) lengkap untuk putra. Dirancang dengan potongan tailor standar nasional yang gagah dan rapi.',
    tags: ['formal', 'upacara', 'putra', 'putih'],
    availableStock: 15,
    material: 'Japan Drill High Quality (Tebal, Dingin, Tidak Mudah Kusut)',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    includedItems: ['Kemeja & Celana PDU', 'Peci Garuda', 'Syal Merah Putih', 'Kendit Pinggang', 'Evolet Bahu', 'Pin Garuda'],
  },
  {
    id: '2',
    name: 'Seragam PDU Paskibraka Putri (Rok)',
    category: 'fullset',
    price: 350000,
    image: 'https://picsum.photos/id/1011/600/800',
    description: 'Pakaian Dinas Upacara (PDU) lengkap untuk putri dengan rok span di bawah lutut. Memberikan kesan anggun namun tetap tegas.',
    tags: ['formal', 'upacara', 'putri', 'rok'],
    availableStock: 15,
    material: 'Japan Drill High Quality',
    sizes: ['S', 'M', 'L', 'XL'],
    includedItems: ['Kemeja & Rok Span', 'Peci Garuda', 'Syal Merah Putih', 'Kendit Pinggang', 'Evolet Bahu', 'Kaos Kaki Putih Panjang'],
  },
  {
    id: '3',
    name: 'Seragam PDU Paskibraka Putri (Celana)',
    category: 'fullset',
    price: 350000,
    image: 'https://picsum.photos/id/1027/600/800',
    description: 'Pakaian Dinas Upacara (PDU) untuk putri yang mengenakan hijab/celana. Potongan longgar namun tetap membentuk siluet tegap.',
    tags: ['formal', 'upacara', 'putri', 'celana', 'hijab'],
    availableStock: 0, 
    material: 'Japan Drill High Quality',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    includedItems: ['Kemeja & Celana Panjang', 'Peci Garuda', 'Syal Merah Putih', 'Kendit Pinggang', 'Evolet Bahu'],
  },
  {
    id: '4',
    name: 'Set Atribut Evolet & Pangkat',
    category: 'aksesoris',
    price: 45000,
    image: 'https://picsum.photos/id/104/500/500',
    description: 'Set evolet bahu dan tanda pangkat bordir emas kualitas premium. Menambah kewibawaan pasukan.',
    tags: ['aksesoris', 'pangkat', 'emas'],
    availableStock: 50,
    material: 'Bordir Komputer Benang Emas',
    sizes: ['All Size'],
    includedItems: ['Sepasang Evolet Bahu', 'Sepasang Tanda Pangkat (Bisa Request Tingkatan)'],
  },
  {
    id: '5',
    name: 'Sepatu PDH Pantofel Hitam Mengkilap',
    category: 'aksesoris',
    price: 75000,
    image: 'https://picsum.photos/id/1071/500/500',
    description: 'Sepatu pantofel bahan kulit sintetis premium, nyaman dipakai baris-berbaris lama. Sol anti-slip dan tidak berisik.',
    tags: ['sepatu', 'aksesoris', 'hitam'],
    availableStock: 30,
    material: 'Kulit Sintetis Glossy (Kilap)',
    sizes: ['37', '38', '39', '40', '41', '42', '43', '44'],
    includedItems: ['Sepasang Sepatu', 'Box Penyimpanan'],
  },
  {
    id: '6',
    name: 'Peci Paskibra Garuda',
    category: 'aksesoris',
    price: 25000,
    image: 'https://picsum.photos/id/111/500/500',
    description: 'Peci hitam bahan beludru halus dengan pin Garuda emas yang kokoh. Standar nasional.',
    tags: ['topi', 'aksesoris', 'kepala'],
    availableStock: 100,
    material: 'Beludru Contessa Super',
    sizes: ['No. 5', 'No. 6', 'No. 7', 'No. 8', 'No. 9'],
    includedItems: ['Peci', 'Pin Garuda Logam'],
  },
  {
    id: '7',
    name: 'Seragam Latihan Lapangan (PDL)',
    category: 'pria',
    price: 150000,
    image: 'https://picsum.photos/id/1001/600/800',
    description: 'Seragam Pakaian Dinas Lapangan loreng/polos untuk latihan fisik. Bahan ripstop kuat dan menyerap keringat.',
    tags: ['latihan', 'outdoor', 'tangguh'],
    availableStock: 20,
    material: 'Ripstop Tornado (Kuat & Cepat Kering)',
    sizes: ['M', 'L', 'XL'],
    includedItems: ['Kemeja PDL', 'Celana Cargo PDL'],
  },
  {
    id: '8',
    name: 'Sarung Tangan Putih (1 Lusin)',
    category: 'aksesoris',
    price: 120000,
    image: 'https://picsum.photos/id/201/500/500',
    description: 'Sarung tangan katun putih tebal. Harga untuk 12 pasang. Wajib untuk upacara bendera agar tangan tidak licin.',
    tags: ['aksesoris', 'tangan', 'grosir'],
    availableStock: 200,
    material: 'Katun Spandek (Melar & Halus)',
    sizes: ['All Size Dewasa'],
    includedItems: ['12 Pasang Sarung Tangan'],
  }
];

export const APP_NAME = "PaskibraRent";
export const CONTACT_WA = "6281234567890";