import { Costume } from './types';

export const COSTUMES: Costume[] = [
  {
    id: '1',
    name: 'Seragam PDU Paskibraka Putra (Lengkap)',
    category: 'fullset',
    price: 350000,
    image: '/images/1.jpeg',
    description: 'Pakaian Dinas Upacara (PDU) lengkap untuk putra. Dirancang dengan potongan tailor standar nasional yang gagah dan rapi.',
    tags: ['formal', 'upacara', 'putra', 'putih'],
    availableStock: 15,
    material: 'Japan Drill High Quality (Tebal, Dingin, Tidak Mudah Kusut)',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    includedItems: ['Kemeja & Celana PDU', 'Peci Garuda', 'Syal Merah Putih', 'Kendit Pinggang', 'Evolet Bahu', 'Pin Garuda'],
  },
  {
    id: '2',
    name: 'Seragam PDU Paskibraka Putri (Rok)',
    category: 'fullset',
    price: 350000,
    image: '/images/WhatsApp Image 2026-02-05 at 21.10.11.jpeg',
    description: 'Pakaian Dinas Upacara (PDU) lengkap untuk putri dengan rok span di bawah lutut. Memberikan kesan anggun namun tetap tegas.',
    tags: ['formal', 'upacara', 'putri', 'rok'],
    availableStock: 15,
    material: 'Japan Drill High Quality',
    sizes: ['S', 'M', 'L', 'XL'],
    includedItems: ['Kemeja & Rok Span', 'Peci Garuda', 'Syal Merah Putih', 'Kendit Pinggang', 'Evolet Bahu', 'Kaos Kaki Putih Panjang'],
  },
  {
    id: '3',
    name: 'Seragam PDU Paskibraka Putri (Celana)',
    category: 'fullset',
    price: 350000,
    image: '/images/WhatsApp Image 2026-02-05 at 21.10.12.jpeg',
    description: 'Pakaian Dinas Upacara (PDU) untuk putri yang mengenakan hijab/celana. Potongan longgar namun tetap membentuk siluet tegap.',
    tags: ['formal', 'upacara', 'putri', 'celana', 'hijab'],
    availableStock: 10,
    material: 'Japan Drill High Quality',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    includedItems: ['Kemeja & Celana Panjang', 'Peci Garuda', 'Syal Merah Putih', 'Kendit Pinggang', 'Evolet Bahu'],
  },
  {
    id: '4',
    name: 'Set Atribut Evolet & Pangkat',
    category: 'aksesoris',
    price: 45000,
    image: '/images/WhatsApp Image 2026-02-05 at 21.17.00.jpeg',
    description: 'Set evolet bahu dan tanda pangkat bordir emas kualitas premium. Menambah kewibawaan pasukan.',
    tags: ['aksesoris', 'pangkat', 'emas'],
    availableStock: 50,
    material: 'Bordir Komputer Benang Emas',
    sizes: ['All Size'],
    includedItems: ['Sepasang Evolet Bahu', 'Sepasang Tanda Pangkat (Bisa Request Tingkatan)'],
  },
  {
    id: '5',
    name: 'Sepatu PDH Pantofel Hitam Mengkilap',
    category: 'aksesoris',
    price: 75000,
    image: '/images/WhatsApp Image 2026-02-05 at 21.10.13.jpeg',
    description: 'Sepatu pantofel bahan kulit sintetis premium, nyaman dipakai baris-berbaris lama. Sol anti-slip dan tidak berisik.',
    tags: ['sepatu', 'aksesoris', 'hitam'],
    availableStock: 30,
    material: 'Kulit Sintetis Glossy (Kilap)',
    sizes: ['37', '38', '39', '40', '41', '42', '43', '44'],
    includedItems: ['Sepasang Sepatu', 'Box Penyimpanan'],
  },
  {
    id: '6',
    name: 'Peci Paskibra Garuda',
    category: 'aksesoris',
    price: 25000,
    image: '/images/WhatsApp Image 2026-02-05 at 21.10.14.jpeg',
    description: 'Peci hitam bahan beludru halus dengan pin Garuda emas yang kokoh. Standar nasional.',
    tags: ['topi', 'aksesoris', 'kepala'],
    availableStock: 100,
    material: 'Beludru Contessa Super',
    sizes: ['No. 5', 'No. 6', 'No. 7', 'No. 8', 'No. 9'],
    includedItems: ['Peci', 'Pin Garuda Logam'],
  },
  {
    id: '7',
    name: 'Seragam Latihan Lapangan (PDL)',
    category: 'pria',
    price: 150000,
    image: '/images/WhatsApp Image 2026-02-05 at 21.16.59.jpeg',
    description: 'Seragam Pakaian Dinas Lapangan loreng/polos untuk latihan fisik. Bahan ripstop kuat dan menyerap keringat.',
    tags: ['latihan', 'outdoor', 'tangguh'],
    availableStock: 20,
    material: 'Ripstop Tornado (Kuat & Cepat Kering)',
    sizes: ['M', 'L', 'XL'],
    includedItems: ['Kemeja PDL', 'Celana Cargo PDL'],
  },
  {
    id: '8',
    name: 'Sarung Tangan Putih (1 Lusin)',
    category: 'aksesoris',
    price: 120000,
    image: '/images/ee.jpeg',
    description: 'Sarung tangan katun putih tebal. Harga untuk 12 pasang. Wajib untuk upacara bendera agar tangan tidak licin.',
    tags: ['aksesoris', 'tangan', 'grosir'],
    availableStock: 200,
    material: 'Katun Spandek (Melar & Halus)',
    sizes: ['All Size Dewasa'],
    includedItems: ['12 Pasang Sarung Tangan'],
  },
  {
    id: '9',
    name: 'Seragam PDU Hijau (Putri)',
    category: 'wanita',
    price: 375000,
    image: '/images/qq.jpeg',
    description: 'Seragam PDU lengkap untuk putri dengan warna hijau menawan. Potongan presisi memberikan kesan wibawa yang kuat.',
    tags: ['formal', 'upacara', 'putri', 'hijau'],
    availableStock: 10,
    material: 'Japan Drill Premium',
    sizes: ['S', 'M', 'L', 'XL'],
    includedItems: ['Kemeja & Celana/Rok', 'Peci Garuda', 'Syal', 'Kendit', 'Atribut Lengkap'],
  },
  {
    id: '10',
    name: 'Seragam Variasi Nusantara (Hitam/Emas)',
    category: 'fullset',
    price: 450000,
    image: '/images/tt.jpeg',
    description: 'Seragam variasi dengan sentuhan etnik nusantara berwarna hitam dan emas. Sangat cocok untuk lomba variasi formasi.',
    tags: ['variasi', 'lomba', 'etnik', 'hitam', 'emas'],
    availableStock: 16,
    material: 'High Twist & Songket',
    sizes: ['S', 'M', 'L', 'XL'],
    includedItems: ['Atasan & Bawahan Variasi', 'Aksesoris Kepala', 'Selempang'],
  },
  {
    id: '11',
    name: 'Seragam Komandan Pasukan (Abu-abu)',
    category: 'pria',
    price: 400000,
    image: '/images/ww.jpeg',
    description: 'Seragam khusus untuk komandan pasukan dengan detail ornamen emas yang mewah pada warna dasar abu-abu elegan.',
    tags: ['komandan', 'pria', 'mewah', 'abu-abu'],
    availableStock: 5,
    material: 'Wool Premium',
    sizes: ['M', 'L', 'XL'],
    includedItems: ['Setelan Jas Komandan', 'Topi Pet', 'Sepatu PDH', 'Sarung Tangan'],
  },
  {
    id: '12',
    name: 'Seragam Pasukan Parade (Biru/Emas)',
    category: 'fullset',
    price: 425000,
    image: '/images/WhatsApp Image 2026-02-05 at 21.18.04.jpeg',
    description: 'Seragam parade dengan kombinasi warna biru dan emas yang cerah. Menonjolkan kekompakan dan semangat pasukan.',
    tags: ['parade', 'lomba', 'biru', 'emas'],
    availableStock: 20,
    material: 'Drill Castillo',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    includedItems: ['Seragam Parade Lengkap', 'Topi Variasi', 'Aksesoris Bahu'],
  },
  {
    id: '13',
    name: 'Seragam Variasi Komandan (Malam)',
    category: 'pria',
    price: 450000,
    image: '/images/WhatsApp Image 2026-02-05 at 21.19.08.jpeg',
    description: 'Varian malam untuk seragam komandan dengan detail emas yang memantulkan cahaya. Tampil memukau di bawah sorotan lampu.',
    tags: ['komandan', 'malam', 'hitam', 'emas'],
    availableStock: 3,
    material: 'High Twist Premium',
    sizes: ['L', 'XL'],
    includedItems: ['Setelan Komandan Malam', 'Topi Pet', 'Aksesoris Emas'],
  },
  {
    id: '14',
    name: 'Seragam PDU Hijau (Putra)',
    category: 'pria',
    price: 375000,
    image: '/images/qq.jpeg',
    description: 'Seragam PDU lengkap untuk putra berwarna hijau. Tampil gagah dengan potongan slim-fit dan atribut lengkap.',
    tags: ['formal', 'upacara', 'pria', 'hijau'],
    availableStock: 10,
    material: 'Japan Drill Premium',
    sizes: ['S', 'M', 'L', 'XL'],
    includedItems: ['Kemeja & Celana', 'Peci Garuda', 'Syal', 'Kendit', 'Sepatu PDH'],
  },
  {
    id: '15',
    name: 'Seragam Variasi Putri (Hitam/Emas)',
    category: 'wanita',
    price: 450000,
    image: '/images/WhatsApp Image 2026-02-05 at 21.10.11.jpeg',
    description: 'Seragam variasi khusus putri dengan hijab, berwarna hitam elegan dengan ornamen emas. Cocok untuk formasi baris-berbaris.',
    tags: ['variasi', 'lomba', 'wanita', 'hitam', 'emas'],
    availableStock: 12,
    material: 'High Twist & Bordir',
    sizes: ['S', 'M', 'L'],
    includedItems: ['Atasan & Bawahan Rok/Celana', 'Hijab Variasi', 'Aksesoris'],
  }
];

export const APP_NAME = "PaskibraRent";
export const CONTACT_WA = "6281234567890";
