import { Costume } from './types';

export const COSTUMES: Costume[] = [
  {
    id: '1',
    name: 'Seragam KOPASKA (Hijau)',
    category: 'fullset',
    price: 375000,
    image: '/images/1.jpeg',
    description: 'Seragam kebanggaan KOPASKA dengan warna hijau khas yang melambangkan ketangguhan dan harmoni. Potongan presisi untuk penampilan terbaik.',
    tags: ['kopaska', 'hijau', 'fullset', 'seragam'],
    availableStock: 20,
    material: 'Japan Drill Premium',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    includedItems: ['Kemeja & Celana/Rok Hijau', 'Peci Garuda', 'Syal', 'Kendit', 'Atribut'],
  },
  {
    id: '2',
    name: 'Seragam ARJUNA (Biru)',
    category: 'fullset',
    price: 425000,
    image: '/images/WhatsApp Image 2026-02-05 at 21.19.08.jpeg',
    description: 'Seragam ARJUNA dengan kombinasi warna biru dan emas yang elegan. Dirancang untuk pasukan yang ingin tampil beda dan memukau.',
    tags: ['arjuna', 'biru', 'fullset', 'seragam'],
    availableStock: 20,
    material: 'Drill Castillo High Quality',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    includedItems: ['Seragam Parade Biru', 'Topi Variasi', 'Aksesoris Bahu Emas'],
  },
  {
    id: '3',
    name: 'Seragam SHERIF (Hitam/Emas)',
    category: 'fullset',
    price: 450000,
    image: '/images/tt.jpeg',
    description: 'Seragam SHERIF berwarna hitam pekat dengan ornamen emas mewah. Pilihan utama untuk variasi formasi yang memberikan kesan kuat dan disiplin.',
    tags: ['sherif', 'hitam', 'emas', 'fullset'],
    availableStock: 16,
    material: 'High Twist Premium & Songket',
    sizes: ['S', 'M', 'L', 'XL'],
    includedItems: ['Atasan & Bawahan Hitam Emas', 'Aksesoris Kepala', 'Selempang Emas'],
  },
  {
    id: '4',
    name: 'Set Atribut Evolet & Pangkat',
    category: 'aksesoris',
    price: 45000,
    image: '/images/WhatsApp Image 2026-02-05 at 21.17.00.jpeg',
    description: 'Set evolet bahu dan tanda pangkat bordir emas kualitas premium. Menambah kewibawaan pasukan.',
    tags: ['aksesoris', 'pangkat', 'emas'],
    availableStock: 50,
    material: 'Bordir Komputer Benang Emas',
    sizes: ['All Size'],
    includedItems: ['Sepasang Evolet Bahu', 'Sepasang Tanda Pangkat (Bisa Request Tingkatan)'],
  },
  {
    id: '5',
    name: 'Sepatu PDH Pantofel Hitam Mengkilap',
    category: 'aksesoris',
    price: 75000,
    image: '/images/WhatsApp Image 2026-02-05 at 21.10.13.jpeg',
    description: 'Sepatu pantofel bahan kulit sintetis premium, nyaman dipakai baris-berbaris lama. Sol anti-slip dan tidak berisik.',
    tags: ['sepatu', 'aksesoris', 'hitam'],
    availableStock: 30,
    material: 'Kulit Sintetis Glossy (Kilap)',
    sizes: ['37', '38', '39', '40', '41', '42', '43', '44'],
    includedItems: ['Sepasang Sepatu', 'Box Penyimpanan'],
  },
  {
    id: '6',
    name: 'Peci Paskibra Garuda',
    category: 'aksesoris',
    price: 25000,
    image: '/images/WhatsApp Image 2026-02-05 at 21.10.14.jpeg',
    description: 'Peci hitam bahan beludru halus dengan pin Garuda emas yang kokoh. Standar nasional.',
    tags: ['topi', 'aksesoris', 'kepala'],
    availableStock: 100,
    material: 'Beludru Contessa Super',
    sizes: ['No. 5', 'No. 6', 'No. 7', 'No. 8', 'No. 9'],
    includedItems: ['Peci', 'Pin Garuda Logam'],
  },
  {
    id: '7',
    name: 'Sarung Tangan Putih (1 Lusin)',
    category: 'aksesoris',
    price: 120000,
    image: '/images/ee.jpeg',
    description: 'Sarung tangan katun putih tebal. Harga untuk 12 pasang. Wajib untuk upacara bendera agar tangan tidak licin.',
    tags: ['aksesoris', 'tangan', 'grosir'],
    availableStock: 200,
    material: 'Katun Spandek (Melar & Halus)',
    sizes: ['All Size Dewasa'],
    includedItems: ['12 Pasang Sarung Tangan'],
  }
];

export const APP_NAME = "KostumFadilyss";
export const CONTACT_WA = "62895428282092";
